Neal week 8 submissions
bootcamp-students/s24-warmups pull request #250
Opened 2024-05-23 12:21 UTC by KumarG23

2024-05-25 19:10 UTC, emberborja requested changes

2024-05-25 19:10 UTC, emberborja commented on neal-sharma/day-36/monsters.py
remove print statements please

2024-05-28 11:53 UTC, KumarG23 commented on neal-sharma/day-36/monsters.py
just removed the prints.

2024-06-03 13:18 UTC, emberborja approved these changes

2024-06-03 13:18 UTC, merged