week 8 submissions
bootcamp-students/s24-warmups pull request #297
Opened 2024-05-27 21:13 UTC by Skell87

should be up to date with kata submissions up to the 27th.

2024-05-28 13:35 UTC, emberborja requested changes

2024-05-28 13:35 UTC, emberborja commented on brandon-heisler/day-34/simple-exists.sql
rename this using snake_case. simple_exists.sql

2024-05-28 13:35 UTC, emberborja commented on brandon-heisler/day-36/kill_the_monsters.py
remove # TODO, you fulfilled this comment by putting in your code :)

2024-05-28 16:52 UTC, Skell87 commented
Made the necessary changes for you

2024-06-03 13:30 UTC, emberborja approved these changes

2024-06-03 13:30 UTC, merged